services:
  app:
    image: alaminislam34/techsoi-bd:latest
    build:
      context: .
      target: dev
    container_name: techsoi-bd
    restart: unless-stopped
    command: sh -c "corepack pnpm install && corepack pnpm exec next dev --hostname 0.0.0.0"
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: 0.0.0.0
      CI: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next