import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";

// import NavbarTop from "@/components/section/NavbarTop";
import Navbar from "@/components/section/Navbar";
import Manubar from "@/components/section/Manubar";
import NavbarCategory from "@/components/section/NavbarCategory";
import Footer from "@/components/section/Footer";
import { AuthProvider } from "@/Provider/AuthProvider";
import QueryProvider from "@/Provider/QueryProvider";

import "./globals.css";
import { ToastContainer } from "react-toastify";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
});

export const metadata: Metadata = {
  title: "Techsoi BD",
  description: "Generated by Techsoi BD",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <QueryProvider>
        <AuthProvider>
          <body className={dmSans.className}>
            {/* Global Navbar */}
            {/* <NavbarTop /> */}
            <Navbar />
            <Manubar />
            <NavbarCategory />
            {/* Page Content */}
            <main>{children}</main>
            {/* Global Footer */}
            <Footer />
            <ToastContainer
              position="top-center"
              autoClose={2000}
              hideProgressBar={false}
            />{" "}
          </body>
        </AuthProvider>
      </QueryProvider>
    </html>
  );
}
