import type { Metadata } from "next";

// import NavbarTop from "@/components/section/NavbarTop";
import Navbar from "@/components/section/Navbar";
import NavbarTop from "@/components/section/NavbarTop";
import Manubar from "@/components/section/Manubar";
import NavbarCategory from "@/components/section/NavbarCategory";
import Footer from "@/components/section/Footer";
import { AuthProvider } from "@/Provider/AuthProvider";
import QueryProvider from "@/Provider/QueryProvider";

import "./globals.css";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Techsoi BD",
  description: "Generated by Techsoi BD",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <QueryProvider>
          <AuthProvider>
            {/* Global Navbar */}
            <NavbarTop />
            <Navbar />
            <Manubar />
            <NavbarCategory />
            {/* Page Content */}
            <main>{children}</main>
            {/* Global Footer */}
            <Footer />
            <ToastContainer
              position="top-center"
              autoClose={2000}
              hideProgressBar={false}
            />{" "}
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
